ktor {
    development = true
    deployment {
        port = 8080
        watch = [ classes, resources ]
    }
    application {
        modules = [ com.example.gooddeedfeed.ApplicationKt.module ]
    }
    database {
        url = ${DB_URL}
        user = ${DB_USER}
        password = ${DB_PASSWORD}
    }
    jwt {
        secret = "Qw8v2n3Xy7Zp4R1s6T0u9L5k2J8h3B6c"
    }
} 