"""Add share_profile_picture field to users table

Revision ID: 003_add_share_profile_picture_field
Revises: 002_add_user_subscriptions_table
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_share_profile_picture_field'
down_revision = '002_add_user_subscriptions_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('share_profile_picture', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'share_profile_picture')
    # ### end Alembic commands ###
